package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

func main() {
	var (
		typeName = flag.String("type", "", "struct type to generate paths for")
		outFile  = flag.String("out", "", "output file path (default: <type>_ojson_paths.go)")
		dir      = flag.String("dir", ".", "package directory")
	)
	flag.Parse()
	if *typeName == "" {
		fatalf("-type is required")
	}
	if *outFile == "" {
		*outFile = filepath.Join(*dir, toSnake(*typeName)+"_ojson_paths.go")
	}

	code, err := generate(*dir, *typeName)
	if err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(*outFile, code, 0o644); err != nil {
		fatalf("write %s: %v", *outFile, err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "ojson-paths: "+format+"\n", args...)
	os.Exit(1)
}

type structInfo struct {
	name   string
	fields []fieldInfo
}

type fieldInfo struct {
	goName     string
	jsonName   string
	typeExpr   string
	nestedName string
	isSlice    bool
	elemType   string
}

func generate(dir, typeName string) ([]byte, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") && !strings.HasSuffix(name, "_ojson_paths.go")
	}, 0)
	if err != nil {
		return nil, err
	}
	if len(pkgs) != 1 {
		return nil, fmt.Errorf("expected one package in %s, found %d", dir, len(pkgs))
	}
	var pkg *ast.Package
	for _, p := range pkgs {
		pkg = p
	}

	rawStructs := map[string]*ast.StructType{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				rawStructs[typeSpec.Name.Name] = structType
			}
		}
	}

	structs := map[string]*structInfo{}
	for name, structType := range rawStructs {
		info, err := readStruct(name, structType)
		if err != nil {
			return nil, err
		}
		structs[name] = info
	}

	root, ok := structs[typeName]
	if !ok {
		return nil, fmt.Errorf("struct type %s not found in %s", typeName, dir)
	}
	if err := validateNested(root, structs, map[string]bool{}); err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by ojson-paths; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)
	neededImports := map[string]bool{"github.com/JohnAD/ojson": true}
	collectImports(root, structs, neededImports)
	buf.WriteString("import (\n")
	paths := make([]string, 0, len(neededImports))
	for path := range neededImports {
		paths = append(paths, path)
	}
	sortStrings(paths)
	for _, path := range paths {
		fmt.Fprintf(&buf, "\t%q\n", path)
	}
	buf.WriteString(")\n\n")

	writePathTypes(&buf, typeName, root, structs)
	writePathVar(&buf, typeName, root, structs)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

func readStruct(name string, structType *ast.StructType) (*structInfo, error) {
	info := &structInfo{name: name}
	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			return nil, fmt.Errorf("%s: embedded fields are not supported by ojson-paths", name)
		}
		for _, ident := range field.Names {
			if !ident.IsExported() {
				continue
			}
			jsonName, skip, err := jsonTagName(field.Tag)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, ident.Name, err)
			}
			if skip {
				continue
			}
			fi := fieldInfo{goName: ident.Name, jsonName: jsonName}
			typeExpr, isSlice, elem, nestedName, err := describeType(field.Type)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, ident.Name, err)
			}
			fi.typeExpr = typeExpr
			fi.isSlice = isSlice
			fi.elemType = elem
			fi.nestedName = nestedName
			info.fields = append(info.fields, fi)
		}
	}
	return info, nil
}

func validateNested(info *structInfo, structs map[string]*structInfo, stack map[string]bool) error {
	if stack[info.name] {
		return fmt.Errorf("recursive struct %s is not supported", info.name)
	}
	stack[info.name] = true
	defer delete(stack, info.name)
	for _, field := range info.fields {
		if field.nestedName == "" {
			continue
		}
		nested, ok := structs[field.nestedName]
		if !ok {
			// External or non-struct named type used as leaf (e.g. custom string alias in same package).
			continue
		}
		// Only nest path structs for actual structs.
		if err := validateNested(nested, structs, stack); err != nil {
			return err
		}
	}
	return nil
}

func describeType(expr ast.Expr) (typeExpr string, isSlice bool, elemType string, nestedStruct string, err error) {
	switch typed := expr.(type) {
	case *ast.StarExpr:
		return describeType(typed.X)
	case *ast.Ident:
		switch typed.Name {
		case "string", "bool", "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"float32", "float64":
			return typed.Name, false, "", "", nil
		default:
			return typed.Name, false, "", typed.Name, nil
		}
	case *ast.SelectorExpr:
		pkg, ok := typed.X.(*ast.Ident)
		if !ok {
			return "", false, "", "", fmt.Errorf("unsupported selector type")
		}
		return pkg.Name + "." + typed.Sel.Name, false, "", "", nil
	case *ast.ArrayType:
		if typed.Len != nil {
			return "", false, "", "", fmt.Errorf("fixed arrays are not supported; use slices")
		}
		elemExpr, _, _, nested, err := describeType(typed.Elt)
		if err != nil {
			return "", false, "", "", err
		}
		return "[]" + elemExpr, true, elemExpr, nested, nil
	case *ast.MapType:
		return "", false, "", "", fmt.Errorf("map fields are not supported for typed paths")
	case *ast.InterfaceType:
		return "", false, "", "", fmt.Errorf("interface fields are not supported for typed paths")
	default:
		return "", false, "", "", fmt.Errorf("unsupported field type")
	}
}

func jsonTagName(tag *ast.BasicLit) (string, bool, error) {
	if tag == nil {
		return "", false, fmt.Errorf("missing json tag")
	}
	value := strings.Trim(tag.Value, "`")
	for _, part := range strings.Split(value, " ") {
		if !strings.HasPrefix(part, "json:") {
			continue
		}
		raw := strings.Trim(strings.TrimPrefix(part, "json:"), `"`)
		if raw == "-" {
			return "", true, nil
		}
		name, _, _ := strings.Cut(raw, ",")
		if name == "" {
			return "", false, fmt.Errorf("json tag must include an explicit name")
		}
		return name, false, nil
	}
	return "", false, fmt.Errorf("missing json tag")
}

func collectImports(root *structInfo, structs map[string]*structInfo, needed map[string]bool) {
	var walk func(*structInfo)
	walk = func(info *structInfo) {
		if info == nil {
			return
		}
		for _, field := range info.fields {
			typeName := field.typeExpr
			if field.isSlice {
				typeName = field.elemType
			}
			if strings.HasPrefix(typeName, "time.") {
				needed["time"] = true
			}
			if strings.HasPrefix(typeName, "json.") {
				needed["encoding/json"] = true
			}
			if field.nestedName != "" {
				if nested, ok := structs[field.nestedName]; ok {
					walk(nested)
				}
			}
		}
	}
	walk(root)
}

func isStructType(name string, structs map[string]*structInfo) bool {
	_, ok := structs[name]
	return ok
}

func writePathTypes(buf *bytes.Buffer, docType string, root *structInfo, structs map[string]*structInfo) {
	written := map[string]bool{}
	var writeType func(info *structInfo)
	writeType = func(info *structInfo) {
		typeName := pathStructName(docType, info.name)
		if written[typeName] {
			return
		}
		written[typeName] = true
		for _, field := range info.fields {
			if field.nestedName != "" && isStructType(field.nestedName, structs) && !field.isSlice {
				writeType(structs[field.nestedName])
			}
		}
		fmt.Fprintf(buf, "type %s struct {\n", typeName)
		for _, field := range info.fields {
			if field.nestedName != "" && isStructType(field.nestedName, structs) && !field.isSlice {
				fmt.Fprintf(buf, "\t%s %s\n", field.goName, pathStructName(docType, field.nestedName))
				continue
			}
			fmt.Fprintf(buf, "\t%s ojson.TypedPath[%s, %s]\n", field.goName, docType, field.typeExpr)
		}
		buf.WriteString("}\n\n")
	}
	writeType(root)
}

func writePathVar(buf *bytes.Buffer, docType string, root *structInfo, structs map[string]*structInfo) {
	fmt.Fprintf(buf, "var %sPaths = %s{\n", docType, pathStructName(docType, root.name))
	writePathVarFields(buf, docType, root, structs, "", 1)
	buf.WriteString("}\n")
}

func writePathVarFields(buf *bytes.Buffer, docType string, info *structInfo, structs map[string]*structInfo, prefix string, indent int) {
	pad := strings.Repeat("\t", indent)
	for _, field := range info.fields {
		pointer := prefix + "/" + escapePointer(field.jsonName)
		if field.nestedName != "" && isStructType(field.nestedName, structs) && !field.isSlice {
			fmt.Fprintf(buf, "%s%s: %s{\n", pad, field.goName, pathStructName(docType, field.nestedName))
			writePathVarFields(buf, docType, structs[field.nestedName], structs, pointer, indent+1)
			fmt.Fprintf(buf, "%s},\n", pad)
			continue
		}
		fmt.Fprintf(buf, "%s%s: ojson.NewTypedPath[%s, %s](%q),\n", pad, field.goName, docType, field.typeExpr, pointer)
	}
}

func pathStructName(docType, structName string) string {
	if structName == docType {
		return unexported(docType) + "Paths"
	}
	return unexported(docType) + structName + "Paths"
}

func unexported(name string) string {
	if name == "" {
		return name
	}
	runes := []rune(name)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func toSnake(name string) string {
	var b strings.Builder
	for i, r := range name {
		if unicode.IsUpper(r) {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func escapePointer(segment string) string {
	segment = strings.ReplaceAll(segment, "~", "~0")
	segment = strings.ReplaceAll(segment, "/", "~1")
	return segment
}

func sortStrings(values []string) {
	for i := 0; i < len(values); i++ {
		for j := i + 1; j < len(values); j++ {
			if values[j] < values[i] {
				values[i], values[j] = values[j], values[i]
			}
		}
	}
}
